# Generated by Django 6.0.3 on 2026-04-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication_entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='refill',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
