# Generated by Django 3.2.5 on 2026-04-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication_entry', '0002_medication_refill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='frequency',
        ),
        migrations.AddField(
            model_name='medication',
            name='dosage_mg',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medication',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='times',
            field=models.JSONField(default=list, help_text="List of times in HH:MM format, e.g., ['09:00', '15:00']"),
        ),
        migrations.AlterField(
            model_name='medication',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='refill',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
