# Generated by Django 6.0.3 on 2026-04-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('Run', 'Run'), ('Walk', 'Walk'), ('Lifting', 'Weight Lifting'), ('Bike', 'Biking'), ('Swim', 'Swim'), ('Other', 'Other')], max_length=15),
        ),
    ]
