# Generated by Django 6.0.3 on 2026-04-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_log', '0002_symptom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
